import "server-only";
import { and, eq, gte, sql } from "drizzle-orm";
import { db } from "@/db";
import { aiUsageLogs } from "@/db/schema";

const GEMINI_API_KEY =
  process.env.GEMINI_API_KEY || process.env.GOOGLE_AI_API_KEY || process.env.GOOGLE_API_KEY;

const MODEL_NAME = process.env.GEMINI_MODEL || "gemini-3.5-flash-lite";

// Anti-misuse limits
const MAX_REQUESTS_PER_MINUTE = 5;
const MAX_REQUESTS_PER_DAY = 50;
const MAX_INPUT_CHARS = 4000;

export async function checkAiRateLimit(userId: string): Promise<{ allowed: boolean; reason?: string }> {
  const now = new Date();
  const oneMinuteAgo = new Date(now.getTime() - 60 * 1000);
  const startOfDay = new Date(now.getFullYear(), now.getMonth(), now.getDate());

  // Check 1-minute rate
  const [minCount] = await db
    .select({ count: sql<number>`count(*)::int` })
    .from(aiUsageLogs)
    .where(and(eq(aiUsageLogs.userId, userId), gte(aiUsageLogs.createdAt, oneMinuteAgo)));

  if ((minCount?.count ?? 0) >= MAX_REQUESTS_PER_MINUTE) {
    return {
      allowed: false,
      reason: "Rate limit reached: Maximum 5 AI actions per minute. Please wait a moment.",
    };
  }

  // Check daily rate
  const [dayCount] = await db
    .select({ count: sql<number>`count(*)::int` })
    .from(aiUsageLogs)
    .where(and(eq(aiUsageLogs.userId, userId), gte(aiUsageLogs.createdAt, startOfDay)));

  if ((dayCount?.count ?? 0) >= MAX_REQUESTS_PER_DAY) {
    return {
      allowed: false,
      reason: "Daily quota reached: Maximum 50 AI actions per user per day.",
    };
  }

  return { allowed: true };
}

export async function recordAiUsage(userId: string, action: string) {
  await db.insert(aiUsageLogs).values({
    userId,
    action,
  }).catch(() => {});
}

export async function callGemini({
  prompt,
  systemInstruction,
  temperature = 0.3,
}: {
  prompt: string;
  systemInstruction?: string;
  temperature?: number;
}): Promise<string> {
  if (!GEMINI_API_KEY) {
    throw new Error("GEMINI_API_KEY is not configured in the environment.");
  }

  // Sanitize and truncate prompt
  const sanitizedPrompt = prompt.slice(0, MAX_INPUT_CHARS);

  const url = `https://generativelanguage.googleapis.com/v1beta/models/${MODEL_NAME}:generateContent?key=${GEMINI_API_KEY}`;

  const requestBody: any = {
    contents: [
      {
        role: "user",
        parts: [{ text: sanitizedPrompt }],
      },
    ],
    generationConfig: {
      temperature,
      maxOutputTokens: 800,
    },
  };

  if (systemInstruction) {
    requestBody.systemInstruction = {
      parts: [{ text: systemInstruction }],
    };
  }

  const res = await fetch(url, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(requestBody),
  });

  if (!res.ok) {
    const errorText = await res.text();
    console.error("Gemini API error:", res.status, errorText);
    throw new Error(`Gemini API error: ${res.statusText}`);
  }

  const data = await res.json();
  const text = data.candidates?.[0]?.content?.parts?.[0]?.text;

  if (!text) {
    throw new Error("No response generated by Gemini.");
  }

  return text.trim();
}
