import crypto from "crypto";
import { eq } from "drizzle-orm";
import { db } from "@/db";
import { projectMembers, projects, users, workspaceMembers, workspaces } from "@/db/schema";
import { getCurrentUser, hashPassword, HttpError, isAdmin } from "@/lib/auth";
import { body, json, route, str } from "@/lib/api";
import { pickAvatarColor } from "@/lib/colors";
import { emailSender } from "@/lib/emailSender";

async function requireAdmin() {
  const user = await getCurrentUser();
  if (!user || !isAdmin(user)) throw new HttpError(403, "Admin only.");
  return user;
}

function generateTempPassword(): string {
  const chars = "abcdefghjkmnpqrstuvwxyz23456789";
  let part1 = "";
  let part2 = "";
  for (let i = 0; i < 4; i++) {
    part1 += chars[crypto.randomInt(0, chars.length)];
    part2 += chars[crypto.randomInt(0, chars.length)];
  }
  return `CLA-${part1}-${part2}`;
}

/** List all human accounts with their workspace memberships. */
export const GET = route(async () => {
  await requireAdmin();
  const rows = await db
    .select({
      id: users.id,
      email: users.email,
      name: users.name,
      color: users.color,
      photoUrl: users.photoUrl,
      userType: users.userType,
      lastActiveAt: users.lastActiveAt,
      createdAt: users.createdAt,
    })
    .from(users)
    .where(eq(users.kind, "human"))
    .orderBy(users.createdAt);

  const memberships = await db
    .select({
      userId: workspaceMembers.userId,
      workspaceId: workspaceMembers.workspaceId,
      workspaceName: workspaces.name,
      role: workspaceMembers.role,
    })
    .from(workspaceMembers)
    .innerJoin(workspaces, eq(workspaces.id, workspaceMembers.workspaceId));

  const wsMap = new Map<string, Array<{ id: string; name: string; role: string }>>();
  for (const m of memberships) {
    if (!wsMap.has(m.userId)) wsMap.set(m.userId, []);
    wsMap.get(m.userId)!.push({ id: m.workspaceId, name: m.workspaceName, role: m.role });
  }

  const usersWithWorkspaces = rows.map((u) => ({
    ...u,
    workspaces: wsMap.get(u.id) || [],
  }));

  return json({ users: usersWithWorkspaces });
});

/** Create a new staff or volunteer account. Workspaces are assigned manually or via explicit selection. */
export const POST = route(async (req: Request) => {
  await requireAdmin();
  const input = await body<{
    email?: string;
    name?: string;
    password?: string;
    photoUrl?: string;
    userType?: "staff" | "volunteer";
    workspaceIds?: string[];
  }>(req);

  const email = str(input.email, "Email", { max: 200 }).toLowerCase();
  const name = str(input.name, "Name", { max: 80 });
  const userType = input.userType === "volunteer" ? "volunteer" : "staff";

  if (userType === "staff") {
    if (!email.endsWith("@codingladies.org")) {
      throw new HttpError(400, "Only @codingladies.org emails are allowed for staff accounts.");
    }
  } else {
    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      throw new HttpError(400, "Please enter a valid email address.");
    }
  }

  let password = input.password?.trim();
  let wasAutoGenerated = false;
  if (!password) {
    password = generateTempPassword();
    wasAutoGenerated = true;
  } else if (password.length < 8) {
    throw new HttpError(400, "Password must be at least 8 characters.");
  }

  let photoUrl: string | null = null;
  if (input.photoUrl && typeof input.photoUrl === "string" && input.photoUrl.trim()) {
    const trimmed = input.photoUrl.trim();
    if (!/^https?:\/\//i.test(trimmed)) {
      throw new HttpError(400, "Profile photo must be a valid URL starting with http:// or https://");
    }
    photoUrl = trimmed;
  }

  const existing = await db.select({ id: users.id }).from(users).where(eq(users.email, email)).limit(1);
  if (existing.length) throw new HttpError(409, "An account with that email already exists.");

  const [user] = await db
    .insert(users)
    .values({
      email,
      name,
      passwordHash: await hashPassword(password),
      color: pickAvatarColor(email),
      photoUrl,
      userType,
    })
    .returning({ id: users.id, email: users.email, name: users.name, photoUrl: users.photoUrl, userType: users.userType });

  // Only assign to workspaces if explicitly selected during creation (otherwise managed manually)
  if (Array.isArray(input.workspaceIds) && input.workspaceIds.length > 0) {
    const validWorkspaces = await db
      .select({ id: workspaces.id })
      .from(workspaces);
    const validIds = new Set(validWorkspaces.map((w) => w.id));
    const selected = input.workspaceIds.filter((id) => validIds.has(id));

    if (selected.length > 0) {
      await db
        .insert(workspaceMembers)
        .values(selected.map((wId) => ({ workspaceId: wId, userId: user.id, role: "member" })))
        .onConflictDoNothing();
    }
  }

  // Send welcome email with credentials
  let emailSent = false;
  try {
    const loginUrl = process.env.NEXT_PUBLIC_APP_URL || "https://flow.codingladies.org/login";
    const roleTitle = userType === "volunteer" ? "Volunteer" : "Staff";
    const mailRes = await emailSender.sendEmail({
      to: email,
      email: email,
      subject: `Welcome to CLA Flow — Your ${roleTitle} Account`,
      first_name: name.split(" ")[0] || name,
      html: `
        <p>Hello <strong>${name}</strong>,</p>
        <p>An administrator has created your <strong>${roleTitle.toLowerCase()} account</strong> on <strong>CLA Flow</strong>.</p>
        <div style="background: #e6fffa; border: 1px solid #00BFB3; border-radius: 8px; padding: 14px 18px; margin: 18px 0;">
          <p style="margin: 0 0 6px 0; font-size: 13px; color: #044e47;">Your sign-in credentials:</p>
          <p style="margin: 0 0 4px 0; font-size: 13px;"><strong>Email:</strong> ${email}</p>
          <p style="margin: 0; font-size: 13px;"><strong>Temporary password:</strong> <code style="font-size: 16px; font-weight: bold; color: #00796B; font-family: monospace;">${password}</code></p>
        </div>
        <p>You can change your password anytime after signing in under your Account settings.</p>
        <div style="text-align: center; margin: 24px 0;">
          <a href="${loginUrl}" class="button" style="background-color: #00BFB3; color: #ffffff; text-decoration: none; padding: 12px 28px; border-radius: 8px; font-weight: bold; display: inline-block;">Sign In to CLA Flow</a>
        </div>
      `,
    });
    emailSent = mailRes.success;
  } catch {
    emailSent = false;
  }

  return json({ user, password, wasAutoGenerated, emailSent });
});
